name: Copy React build folder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

#     - name: Install dependencies
#       run: npm install

#     - name: Build React app
#       run: npm run build

    - name: Copy build folder to new path
      run: sudo cp -r build/ /opt/
